import { MigrationInterface, QueryRunner } from "typeorm";

export class Migrations1727152608050 implements MigrationInterface {
    name = 'Migrations1727152608050'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`fund_companies\` (\`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`logo\` varchar(255) NULL, \`mobile\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`commercial_register\` varchar(255) NOT NULL, \`fund_company_type\` enum ('bank', 'finance_company') NOT NULL, \`min_age\` int NOT NULL DEFAULT '0', \`max_age\` int NOT NULL DEFAULT '0', \`Deduction_percentage_without_realstate_finance\` int NOT NULL DEFAULT '45', \`Deduction_percentage_realstate_finance\` int NOT NULL DEFAULT '55', \`Deduction_percentage_support_realstate_finance\` int NOT NULL DEFAULT '65', UNIQUE INDEX \`IDX_02e5661a03de3391f8ddffb5dd\` (\`name\`), UNIQUE INDEX \`IDX_1ef2fbb72e6a60223bee929411\` (\`mobile\`), UNIQUE INDEX \`IDX_c039cf3191de417c2162b77e93\` (\`email\`), UNIQUE INDEX \`IDX_651af7cc2b895f24487860cb40\` (\`commercial_register\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`labor_sector\` (\`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`name_ar\` varchar(255) NOT NULL, \`name_en\` varchar(255) NOT NULL, \`slug\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`offers_lapor_sectors\` (\`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`first_patch\` double NOT NULL, \`last_patch\` double NOT NULL, \`benfit_before_limit\` double NOT NULL, \`benfit_after_limit\` double NOT NULL, \`administrative_fees\` double NOT NULL, \`installment_year\` int NOT NULL, \`salary_type\` enum ('transformed', 'untransformed') NOT NULL, \`nationality\` enum ('Saudi Arabian', 'Residence') NOT NULL, \`laporsectorId\` int NULL, \`offerId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cities\` (\`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`name_ar\` varchar(255) NOT NULL, \`name_en\` varchar(255) NOT NULL, UNIQUE INDEX \`IDX_6c289e215c7d8c4ea3f274c914\` (\`name_ar\`), UNIQUE INDEX \`IDX_355cee4941a3d461e95fea2d45\` (\`name_en\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`fund_company_branches\` (\`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`address\` varchar(255) NOT NULL, \`lat\` double NULL, \`long\` double NULL, \`email\` varchar(255) NOT NULL, \`mobile\` varchar(255) NOT NULL, \`district\` varchar(255) NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`fund_company_id\` int NOT NULL, \`city_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`agency_branches\` (\`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`address\` varchar(255) NOT NULL, \`lat\` double NULL, \`long\` double NULL, \`email\` varchar(255) NOT NULL, \`mobile\` varchar(255) NOT NULL, \`district\` varchar(255) NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`stamp\` varchar(255) NULL, \`signature\` varchar(255) NULL, \`agency_id\` int NOT NULL, \`city_id\` int NOT NULL, UNIQUE INDEX \`IDX_7a146d49148e41cc8624762f3a\` (\`name\`, \`address\`, \`agency_id\`, \`city_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`roles\` (\`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`permissions\` json NOT NULL, \`agency_branch_id\` int NULL, \`funding_branch_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`admins\` (\`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`logo\` varchar(255) NULL, \`email\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`status\` enum ('active', 'hold') NOT NULL DEFAULT 'active', \`type\` enum ('SuperAdmin', 'Agent', 'Funding') NOT NULL, \`role_id\` int NOT NULL, \`agency_id\` int NULL, \`fund_id\` int NULL, UNIQUE INDEX \`IDX_051db7d37d478a69a7432df147\` (\`email\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`attachments_requests\` (\`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`file\` varchar(255) NULL, \`request_id\` int NOT NULL, \`created_by\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`colors\` (\`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`name_en\` varchar(255) NOT NULL, \`name_ar\` varchar(255) NOT NULL, \`hex_code\` varchar(255) NOT NULL, UNIQUE INDEX \`IDX_7ebd35675297312bde25510454\` (\`name_en\`), UNIQUE INDEX \`IDX_87478b727542707afa08266675\` (\`name_ar\`), UNIQUE INDEX \`IDX_add54b5a317371786a73b8b152\` (\`hex_code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`car_prices\` (\`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`price\` decimal(10,2) NOT NULL, \`car_id\` int NOT NULL, \`admin_id\` int NOT NULL, \`agency_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cars\` (\`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`price\` decimal(10,2) NOT NULL, \`year\` int NOT NULL, \`gear_shifter\` enum ('Manual', 'Automatic', 'SemiAutomatic') NULL, \`car_body\` enum ('Hatchback', 'Sedan', 'FourWheelDrive', 'Commercial', 'Family') NULL, \`fuel_type\` enum ('Gasoline', 'Diesel', 'Electric', 'Hybrid') NULL, \`model_id\` int NOT NULL, \`brand_id\` int NOT NULL, \`sub_model_id\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`clients_score\` (\`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`net_salary\` decimal(10,2) NOT NULL, \`support\` int NOT NULL, \`insurance_percentage\` int NOT NULL, \`nationality\` enum ('Saudi Arabian', 'Residence') NOT NULL DEFAULT 'Saudi Arabian', \`monthly_obligations\` decimal(10,2) NOT NULL, \`salary_bank_id\` int NOT NULL, \`mortgage_loan\` tinyint NOT NULL DEFAULT 0, \`mortgage_loan_support\` tinyint NOT NULL DEFAULT 0, \`simah_issue\` tinyint NOT NULL DEFAULT 0, \`employment_date\` date NOT NULL, \`active\` tinyint NOT NULL DEFAULT 1, \`lapor_sector_id\` int NOT NULL, \`client_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`clients\` (\`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`name_ar\` varchar(255) NOT NULL, \`name_en\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`mobile\` varchar(255) NOT NULL, \`birth_date\` date NOT NULL, \`Identity_no\` varchar(255) NULL, \`gender\` enum ('male', 'female') NOT NULL DEFAULT 'male', \`created_by\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`requests_histories\` (\`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`created_by\` int NOT NULL, \`comment\` varchar(255) NOT NULL, \`status\` enum ('New_Request', 'Pending', 'Pending_Nfaz', 'Pending_Mwafqa', 'Pending_Fund_Company', 'Pending_Document', 'Pending_Contract', 'Pending_Delivery', 'Delivered', 'Finished', 'Rejected', 'Approved') NULL DEFAULT 'Pending', \`request_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`requests\` (\`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`first_batch\` int NULL, \`last_batch\` int NULL, \`support\` int NOT NULL, \`instalment_duration\` int NOT NULL, \`insurance_percentage\` int NOT NULL, \`chassis_no\` varchar(255) NULL, \`specifications\` longtext NULL, \`client_score_id\` int NOT NULL, \`client_id\` int NOT NULL, \`offer_id\` int NOT NULL, \`admin_id\` int NOT NULL, \`branch_agency_id\` int NOT NULL, \`car_id\` int NOT NULL, \`color_id\` int NOT NULL, \`car_price_id\` int NULL, \`price\` decimal(10,2) NULL, \`price_after_vat\` decimal(10,2) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`offers\` (\`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`image\` varchar(255) NOT NULL, \`title_ar\` varchar(255) NOT NULL, \`title_en\` varchar(255) NOT NULL, \`description_ar\` varchar(255) NOT NULL, \`description_en\` varchar(255) NOT NULL, \`start_date\` date NOT NULL, \`expiry_date\` date NOT NULL, \`recived_support\` tinyint NOT NULL DEFAULT 0, \`fund_company_id\` int NOT NULL, \`agency_id\` int NOT NULL, \`transformed_min_salary\` double NOT NULL, \`transformed_max_salary\` double NOT NULL, \`untransformed_min_salary\` double NOT NULL, \`untransformed_max_salary\` double NOT NULL, \`years\` text NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`agencies\` (\`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`logo\` varchar(255) NULL, \`mobile\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`commercial_register\` varchar(255) NOT NULL, \`stamp\` varchar(255) NULL, \`commission\` int NOT NULL DEFAULT '0', \`signature\` varchar(255) NULL, UNIQUE INDEX \`IDX_1ea16c73ecef4bab2f61c31c88\` (\`name\`), UNIQUE INDEX \`IDX_2f561aed06ef50b06074ad9cf1\` (\`mobile\`), UNIQUE INDEX \`IDX_d25d2a0363d82243de8434a2e7\` (\`email\`), UNIQUE INDEX \`IDX_ac29004bf7878d2cf5a5e09d28\` (\`commercial_register\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`brands\` (\`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`name_en\` varchar(255) NOT NULL, \`name_ar\` varchar(255) NOT NULL, \`logo\` varchar(255) NULL, UNIQUE INDEX \`IDX_15c9cb95a4bbc80a75f1995ecf\` (\`name_en\`), UNIQUE INDEX \`IDX_ae5f33d7567de896500debc24a\` (\`name_ar\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`models\` (\`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`name_en\` varchar(255) NOT NULL, \`name_ar\` varchar(255) NOT NULL, \`brand_id\` int NOT NULL, UNIQUE INDEX \`IDX_53930e477ef83ab0a59b817259\` (\`name_en\`), UNIQUE INDEX \`IDX_de137d31b741a0a88d9312dd04\` (\`name_ar\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`sub_models\` (\`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`name_en\` varchar(255) NOT NULL, \`name_ar\` varchar(255) NOT NULL, \`model_id\` int NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`uploaded_files\` (\`id\` int NOT NULL AUTO_INCREMENT, \`file\` varchar(255) NOT NULL, \`is_used\` tinyint NOT NULL DEFAULT 0, \`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`commissions\` (\`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`admin_id\` int NOT NULL, \`agency_id\` int NOT NULL, \`branch_agency_id\` int NOT NULL, \`request_id\` int NOT NULL, \`done_request_date\` date NOT NULL, \`commission_percentage\` int NOT NULL, \`value\` decimal(10,2) NOT NULL, \`collected_date\` date NULL, \`is_collected\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`collectioncommission\` (\`created_at\` datetime(6) NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deleted_at\` datetime(6) NULL, \`id\` int NOT NULL AUTO_INCREMENT, \`admin_id\` int NOT NULL, \`from_Date\` date NULL, \`to_Date\` date NULL, \`value\` int NOT NULL, \`number_of_commissions\` int NOT NULL, \`is_collected\` tinyint NOT NULL DEFAULT 0, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`admin_fund_branches\` (\`fundCompanyBranchesId\` int NOT NULL, \`adminsId\` int NOT NULL, INDEX \`IDX_41e32e3de92e4c88a4a81f0a2a\` (\`fundCompanyBranchesId\`), INDEX \`IDX_9fa6cfacbc967a05625a2334df\` (\`adminsId\`), PRIMARY KEY (\`fundCompanyBranchesId\`, \`adminsId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`admin_agency_branches\` (\`agencyBranchesId\` int NOT NULL, \`adminsId\` int NOT NULL, INDEX \`IDX_4b785b347b331e3bca2272124c\` (\`agencyBranchesId\`), INDEX \`IDX_50cd5e8bd7cc7ea941e95e8a06\` (\`adminsId\`), PRIMARY KEY (\`agencyBranchesId\`, \`adminsId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`car_colors\` (\`colorsId\` int NOT NULL, \`carsId\` int NOT NULL, INDEX \`IDX_10bd402333a904e3db3992b7b6\` (\`colorsId\`), INDEX \`IDX_a548289995720460c08fb1dad8\` (\`carsId\`), PRIMARY KEY (\`colorsId\`, \`carsId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`offers_brands\` (\`offersId\` int NOT NULL, \`brandsId\` int NOT NULL, INDEX \`IDX_1431d2e8a870dc5e820086062a\` (\`offersId\`), INDEX \`IDX_b5c09d453b6b02a377efbf6ce9\` (\`brandsId\`), PRIMARY KEY (\`offersId\`, \`brandsId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`offers_models\` (\`offersId\` int NOT NULL, \`modelsId\` int NOT NULL, INDEX \`IDX_1c9c8066b09d53b4001170baf5\` (\`offersId\`), INDEX \`IDX_ceaecb178638ac0accbf6fa32f\` (\`modelsId\`), PRIMARY KEY (\`offersId\`, \`modelsId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`offers_agency\` (\`agenciesId\` int NOT NULL, \`offersId\` int NOT NULL, INDEX \`IDX_5eb924cae75ea3be0d290e26fe\` (\`agenciesId\`), INDEX \`IDX_4bf592d2a8555fd51bbf371f62\` (\`offersId\`), PRIMARY KEY (\`agenciesId\`, \`offersId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`agency_brands\` (\`agenciesId\` int NOT NULL, \`brandsId\` int NOT NULL, INDEX \`IDX_f16baced67c2f0c11dcc293891\` (\`agenciesId\`), INDEX \`IDX_b9a54d3ce9ed52bb803b481671\` (\`brandsId\`), PRIMARY KEY (\`agenciesId\`, \`brandsId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`collection_commission\` (\`collectioncommissionId\` int NOT NULL, \`commissionsId\` int NOT NULL, INDEX \`IDX_cff1a40d1ede76d09a950f7029\` (\`collectioncommissionId\`), INDEX \`IDX_554f4ad180601c22094fb2ff08\` (\`commissionsId\`), PRIMARY KEY (\`collectioncommissionId\`, \`commissionsId\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`offers_lapor_sectors\` ADD CONSTRAINT \`FK_312d729856ff0972d3734f5da24\` FOREIGN KEY (\`laporsectorId\`) REFERENCES \`labor_sector\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`offers_lapor_sectors\` ADD CONSTRAINT \`FK_5327fdc70b68bd4cf3bdd9e0014\` FOREIGN KEY (\`offerId\`) REFERENCES \`offers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`fund_company_branches\` ADD CONSTRAINT \`FK_359f33d325733255f26de719255\` FOREIGN KEY (\`fund_company_id\`) REFERENCES \`fund_companies\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`fund_company_branches\` ADD CONSTRAINT \`FK_b6bd2addbedb075715ef495ca8a\` FOREIGN KEY (\`city_id\`) REFERENCES \`cities\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`agency_branches\` ADD CONSTRAINT \`FK_e0b92bfcd660d966e567852009e\` FOREIGN KEY (\`agency_id\`) REFERENCES \`agencies\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`agency_branches\` ADD CONSTRAINT \`FK_9b89a716922816435b638fe349c\` FOREIGN KEY (\`city_id\`) REFERENCES \`cities\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD CONSTRAINT \`FK_5dbd33adaf88e38733304868abe\` FOREIGN KEY (\`agency_branch_id\`) REFERENCES \`agency_branches\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD CONSTRAINT \`FK_c231afa9354c6c8b67641e060f1\` FOREIGN KEY (\`funding_branch_id\`) REFERENCES \`fund_company_branches\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`admins\` ADD CONSTRAINT \`FK_5733c73cd81c566a90cc4802f96\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`admins\` ADD CONSTRAINT \`FK_3daa2179c1aa8a1c02c86fe1112\` FOREIGN KEY (\`agency_id\`) REFERENCES \`agencies\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`admins\` ADD CONSTRAINT \`FK_5d82e984646bfaa81f1ad3caccd\` FOREIGN KEY (\`fund_id\`) REFERENCES \`fund_companies\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`attachments_requests\` ADD CONSTRAINT \`FK_3222964e0437f911126d8f2f88f\` FOREIGN KEY (\`request_id\`) REFERENCES \`requests\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`attachments_requests\` ADD CONSTRAINT \`FK_7c70afe4b06524a903b12052afe\` FOREIGN KEY (\`created_by\`) REFERENCES \`admins\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`car_prices\` ADD CONSTRAINT \`FK_bb13eace62e6089974a7546bd2f\` FOREIGN KEY (\`car_id\`) REFERENCES \`cars\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`car_prices\` ADD CONSTRAINT \`FK_3e09b31c23709ececa6ac0b0916\` FOREIGN KEY (\`admin_id\`) REFERENCES \`admins\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`car_prices\` ADD CONSTRAINT \`FK_b9c940152d82d33752d8213d591\` FOREIGN KEY (\`agency_id\`) REFERENCES \`agencies\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`cars\` ADD CONSTRAINT \`FK_e2c56ee6f05695da6b1abcb01c1\` FOREIGN KEY (\`model_id\`) REFERENCES \`models\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`cars\` ADD CONSTRAINT \`FK_68ce82c97c062f06685a52b3d60\` FOREIGN KEY (\`brand_id\`) REFERENCES \`brands\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`cars\` ADD CONSTRAINT \`FK_39461c3a771c0970cd9ddb01ced\` FOREIGN KEY (\`sub_model_id\`) REFERENCES \`sub_models\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`clients_score\` ADD CONSTRAINT \`FK_3c57740027d892eea5720697aaf\` FOREIGN KEY (\`salary_bank_id\`) REFERENCES \`fund_companies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`clients_score\` ADD CONSTRAINT \`FK_3b6eccd541455aca25151dec553\` FOREIGN KEY (\`lapor_sector_id\`) REFERENCES \`labor_sector\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`clients_score\` ADD CONSTRAINT \`FK_9d2c1f0ead8c1b1696c89fd34eb\` FOREIGN KEY (\`client_id\`) REFERENCES \`clients\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`clients\` ADD CONSTRAINT \`FK_f48a5f46db8d13a0c8dad0a435d\` FOREIGN KEY (\`created_by\`) REFERENCES \`admins\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`requests_histories\` ADD CONSTRAINT \`FK_61ac1d4e5b0243e1279c3f1f91d\` FOREIGN KEY (\`created_by\`) REFERENCES \`admins\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`requests_histories\` ADD CONSTRAINT \`FK_260cc4c67a230460c358e5b68e4\` FOREIGN KEY (\`request_id\`) REFERENCES \`requests\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`requests\` ADD CONSTRAINT \`FK_78a1b5a5169a1d674c7fd7168f7\` FOREIGN KEY (\`client_score_id\`) REFERENCES \`clients_score\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`requests\` ADD CONSTRAINT \`FK_e336e481a84734861089a92a233\` FOREIGN KEY (\`client_id\`) REFERENCES \`clients\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`requests\` ADD CONSTRAINT \`FK_09c0936a869e44fde492e1e6f1c\` FOREIGN KEY (\`offer_id\`) REFERENCES \`offers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`requests\` ADD CONSTRAINT \`FK_fb0be14ec40bdb07bf419c02139\` FOREIGN KEY (\`color_id\`) REFERENCES \`colors\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`requests\` ADD CONSTRAINT \`FK_ebd0c41189b8400f72819e17043\` FOREIGN KEY (\`admin_id\`) REFERENCES \`admins\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`requests\` ADD CONSTRAINT \`FK_407ea1709b29b6ba4c737177294\` FOREIGN KEY (\`branch_agency_id\`) REFERENCES \`agency_branches\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`requests\` ADD CONSTRAINT \`FK_8d588d2e86d9f6145a073301d53\` FOREIGN KEY (\`car_id\`) REFERENCES \`cars\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`requests\` ADD CONSTRAINT \`FK_661ac7d80f7cb9445678210ca8f\` FOREIGN KEY (\`car_price_id\`) REFERENCES \`car_prices\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`offers\` ADD CONSTRAINT \`FK_cc7f9ca838aab050c4cc460c5a1\` FOREIGN KEY (\`fund_company_id\`) REFERENCES \`fund_companies\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`offers\` ADD CONSTRAINT \`FK_d57c0e0c0f328073f0f948e69f4\` FOREIGN KEY (\`agency_id\`) REFERENCES \`agencies\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`models\` ADD CONSTRAINT \`FK_f2b1673c6665816ff753e81d1a0\` FOREIGN KEY (\`brand_id\`) REFERENCES \`brands\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`sub_models\` ADD CONSTRAINT \`FK_30ab36c347c4635beb15be7e838\` FOREIGN KEY (\`model_id\`) REFERENCES \`models\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`commissions\` ADD CONSTRAINT \`FK_beea728fafb96125eacc817d771\` FOREIGN KEY (\`admin_id\`) REFERENCES \`admins\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`commissions\` ADD CONSTRAINT \`FK_7e305437229efac2aa485da4b83\` FOREIGN KEY (\`agency_id\`) REFERENCES \`agencies\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`commissions\` ADD CONSTRAINT \`FK_e05549e4eff226488e1a0dd07b3\` FOREIGN KEY (\`branch_agency_id\`) REFERENCES \`agency_branches\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`commissions\` ADD CONSTRAINT \`FK_ddbe8089d269035c4a44c7ba103\` FOREIGN KEY (\`request_id\`) REFERENCES \`requests\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`collectioncommission\` ADD CONSTRAINT \`FK_3a31fb9f883b5d427b0af15b2f7\` FOREIGN KEY (\`admin_id\`) REFERENCES \`admins\`(\`id\`) ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`admin_fund_branches\` ADD CONSTRAINT \`FK_41e32e3de92e4c88a4a81f0a2a6\` FOREIGN KEY (\`fundCompanyBranchesId\`) REFERENCES \`fund_company_branches\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`admin_fund_branches\` ADD CONSTRAINT \`FK_9fa6cfacbc967a05625a2334dfa\` FOREIGN KEY (\`adminsId\`) REFERENCES \`admins\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`admin_agency_branches\` ADD CONSTRAINT \`FK_4b785b347b331e3bca2272124cb\` FOREIGN KEY (\`agencyBranchesId\`) REFERENCES \`agency_branches\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`admin_agency_branches\` ADD CONSTRAINT \`FK_50cd5e8bd7cc7ea941e95e8a06a\` FOREIGN KEY (\`adminsId\`) REFERENCES \`admins\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`car_colors\` ADD CONSTRAINT \`FK_10bd402333a904e3db3992b7b66\` FOREIGN KEY (\`colorsId\`) REFERENCES \`colors\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`car_colors\` ADD CONSTRAINT \`FK_a548289995720460c08fb1dad82\` FOREIGN KEY (\`carsId\`) REFERENCES \`cars\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`offers_brands\` ADD CONSTRAINT \`FK_1431d2e8a870dc5e820086062af\` FOREIGN KEY (\`offersId\`) REFERENCES \`offers\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`offers_brands\` ADD CONSTRAINT \`FK_b5c09d453b6b02a377efbf6ce98\` FOREIGN KEY (\`brandsId\`) REFERENCES \`brands\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`offers_models\` ADD CONSTRAINT \`FK_1c9c8066b09d53b4001170baf50\` FOREIGN KEY (\`offersId\`) REFERENCES \`offers\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`offers_models\` ADD CONSTRAINT \`FK_ceaecb178638ac0accbf6fa32fa\` FOREIGN KEY (\`modelsId\`) REFERENCES \`models\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`offers_agency\` ADD CONSTRAINT \`FK_5eb924cae75ea3be0d290e26fe6\` FOREIGN KEY (\`agenciesId\`) REFERENCES \`agencies\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`offers_agency\` ADD CONSTRAINT \`FK_4bf592d2a8555fd51bbf371f628\` FOREIGN KEY (\`offersId\`) REFERENCES \`offers\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`agency_brands\` ADD CONSTRAINT \`FK_f16baced67c2f0c11dcc2938914\` FOREIGN KEY (\`agenciesId\`) REFERENCES \`agencies\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`agency_brands\` ADD CONSTRAINT \`FK_b9a54d3ce9ed52bb803b4816712\` FOREIGN KEY (\`brandsId\`) REFERENCES \`brands\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`collection_commission\` ADD CONSTRAINT \`FK_cff1a40d1ede76d09a950f70298\` FOREIGN KEY (\`collectioncommissionId\`) REFERENCES \`collectioncommission\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`collection_commission\` ADD CONSTRAINT \`FK_554f4ad180601c22094fb2ff087\` FOREIGN KEY (\`commissionsId\`) REFERENCES \`commissions\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`collection_commission\` DROP FOREIGN KEY \`FK_554f4ad180601c22094fb2ff087\``);
        await queryRunner.query(`ALTER TABLE \`collection_commission\` DROP FOREIGN KEY \`FK_cff1a40d1ede76d09a950f70298\``);
        await queryRunner.query(`ALTER TABLE \`agency_brands\` DROP FOREIGN KEY \`FK_b9a54d3ce9ed52bb803b4816712\``);
        await queryRunner.query(`ALTER TABLE \`agency_brands\` DROP FOREIGN KEY \`FK_f16baced67c2f0c11dcc2938914\``);
        await queryRunner.query(`ALTER TABLE \`offers_agency\` DROP FOREIGN KEY \`FK_4bf592d2a8555fd51bbf371f628\``);
        await queryRunner.query(`ALTER TABLE \`offers_agency\` DROP FOREIGN KEY \`FK_5eb924cae75ea3be0d290e26fe6\``);
        await queryRunner.query(`ALTER TABLE \`offers_models\` DROP FOREIGN KEY \`FK_ceaecb178638ac0accbf6fa32fa\``);
        await queryRunner.query(`ALTER TABLE \`offers_models\` DROP FOREIGN KEY \`FK_1c9c8066b09d53b4001170baf50\``);
        await queryRunner.query(`ALTER TABLE \`offers_brands\` DROP FOREIGN KEY \`FK_b5c09d453b6b02a377efbf6ce98\``);
        await queryRunner.query(`ALTER TABLE \`offers_brands\` DROP FOREIGN KEY \`FK_1431d2e8a870dc5e820086062af\``);
        await queryRunner.query(`ALTER TABLE \`car_colors\` DROP FOREIGN KEY \`FK_a548289995720460c08fb1dad82\``);
        await queryRunner.query(`ALTER TABLE \`car_colors\` DROP FOREIGN KEY \`FK_10bd402333a904e3db3992b7b66\``);
        await queryRunner.query(`ALTER TABLE \`admin_agency_branches\` DROP FOREIGN KEY \`FK_50cd5e8bd7cc7ea941e95e8a06a\``);
        await queryRunner.query(`ALTER TABLE \`admin_agency_branches\` DROP FOREIGN KEY \`FK_4b785b347b331e3bca2272124cb\``);
        await queryRunner.query(`ALTER TABLE \`admin_fund_branches\` DROP FOREIGN KEY \`FK_9fa6cfacbc967a05625a2334dfa\``);
        await queryRunner.query(`ALTER TABLE \`admin_fund_branches\` DROP FOREIGN KEY \`FK_41e32e3de92e4c88a4a81f0a2a6\``);
        await queryRunner.query(`ALTER TABLE \`collectioncommission\` DROP FOREIGN KEY \`FK_3a31fb9f883b5d427b0af15b2f7\``);
        await queryRunner.query(`ALTER TABLE \`commissions\` DROP FOREIGN KEY \`FK_ddbe8089d269035c4a44c7ba103\``);
        await queryRunner.query(`ALTER TABLE \`commissions\` DROP FOREIGN KEY \`FK_e05549e4eff226488e1a0dd07b3\``);
        await queryRunner.query(`ALTER TABLE \`commissions\` DROP FOREIGN KEY \`FK_7e305437229efac2aa485da4b83\``);
        await queryRunner.query(`ALTER TABLE \`commissions\` DROP FOREIGN KEY \`FK_beea728fafb96125eacc817d771\``);
        await queryRunner.query(`ALTER TABLE \`sub_models\` DROP FOREIGN KEY \`FK_30ab36c347c4635beb15be7e838\``);
        await queryRunner.query(`ALTER TABLE \`models\` DROP FOREIGN KEY \`FK_f2b1673c6665816ff753e81d1a0\``);
        await queryRunner.query(`ALTER TABLE \`offers\` DROP FOREIGN KEY \`FK_d57c0e0c0f328073f0f948e69f4\``);
        await queryRunner.query(`ALTER TABLE \`offers\` DROP FOREIGN KEY \`FK_cc7f9ca838aab050c4cc460c5a1\``);
        await queryRunner.query(`ALTER TABLE \`requests\` DROP FOREIGN KEY \`FK_661ac7d80f7cb9445678210ca8f\``);
        await queryRunner.query(`ALTER TABLE \`requests\` DROP FOREIGN KEY \`FK_8d588d2e86d9f6145a073301d53\``);
        await queryRunner.query(`ALTER TABLE \`requests\` DROP FOREIGN KEY \`FK_407ea1709b29b6ba4c737177294\``);
        await queryRunner.query(`ALTER TABLE \`requests\` DROP FOREIGN KEY \`FK_ebd0c41189b8400f72819e17043\``);
        await queryRunner.query(`ALTER TABLE \`requests\` DROP FOREIGN KEY \`FK_fb0be14ec40bdb07bf419c02139\``);
        await queryRunner.query(`ALTER TABLE \`requests\` DROP FOREIGN KEY \`FK_09c0936a869e44fde492e1e6f1c\``);
        await queryRunner.query(`ALTER TABLE \`requests\` DROP FOREIGN KEY \`FK_e336e481a84734861089a92a233\``);
        await queryRunner.query(`ALTER TABLE \`requests\` DROP FOREIGN KEY \`FK_78a1b5a5169a1d674c7fd7168f7\``);
        await queryRunner.query(`ALTER TABLE \`requests_histories\` DROP FOREIGN KEY \`FK_260cc4c67a230460c358e5b68e4\``);
        await queryRunner.query(`ALTER TABLE \`requests_histories\` DROP FOREIGN KEY \`FK_61ac1d4e5b0243e1279c3f1f91d\``);
        await queryRunner.query(`ALTER TABLE \`clients\` DROP FOREIGN KEY \`FK_f48a5f46db8d13a0c8dad0a435d\``);
        await queryRunner.query(`ALTER TABLE \`clients_score\` DROP FOREIGN KEY \`FK_9d2c1f0ead8c1b1696c89fd34eb\``);
        await queryRunner.query(`ALTER TABLE \`clients_score\` DROP FOREIGN KEY \`FK_3b6eccd541455aca25151dec553\``);
        await queryRunner.query(`ALTER TABLE \`clients_score\` DROP FOREIGN KEY \`FK_3c57740027d892eea5720697aaf\``);
        await queryRunner.query(`ALTER TABLE \`cars\` DROP FOREIGN KEY \`FK_39461c3a771c0970cd9ddb01ced\``);
        await queryRunner.query(`ALTER TABLE \`cars\` DROP FOREIGN KEY \`FK_68ce82c97c062f06685a52b3d60\``);
        await queryRunner.query(`ALTER TABLE \`cars\` DROP FOREIGN KEY \`FK_e2c56ee6f05695da6b1abcb01c1\``);
        await queryRunner.query(`ALTER TABLE \`car_prices\` DROP FOREIGN KEY \`FK_b9c940152d82d33752d8213d591\``);
        await queryRunner.query(`ALTER TABLE \`car_prices\` DROP FOREIGN KEY \`FK_3e09b31c23709ececa6ac0b0916\``);
        await queryRunner.query(`ALTER TABLE \`car_prices\` DROP FOREIGN KEY \`FK_bb13eace62e6089974a7546bd2f\``);
        await queryRunner.query(`ALTER TABLE \`attachments_requests\` DROP FOREIGN KEY \`FK_7c70afe4b06524a903b12052afe\``);
        await queryRunner.query(`ALTER TABLE \`attachments_requests\` DROP FOREIGN KEY \`FK_3222964e0437f911126d8f2f88f\``);
        await queryRunner.query(`ALTER TABLE \`admins\` DROP FOREIGN KEY \`FK_5d82e984646bfaa81f1ad3caccd\``);
        await queryRunner.query(`ALTER TABLE \`admins\` DROP FOREIGN KEY \`FK_3daa2179c1aa8a1c02c86fe1112\``);
        await queryRunner.query(`ALTER TABLE \`admins\` DROP FOREIGN KEY \`FK_5733c73cd81c566a90cc4802f96\``);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP FOREIGN KEY \`FK_c231afa9354c6c8b67641e060f1\``);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP FOREIGN KEY \`FK_5dbd33adaf88e38733304868abe\``);
        await queryRunner.query(`ALTER TABLE \`agency_branches\` DROP FOREIGN KEY \`FK_9b89a716922816435b638fe349c\``);
        await queryRunner.query(`ALTER TABLE \`agency_branches\` DROP FOREIGN KEY \`FK_e0b92bfcd660d966e567852009e\``);
        await queryRunner.query(`ALTER TABLE \`fund_company_branches\` DROP FOREIGN KEY \`FK_b6bd2addbedb075715ef495ca8a\``);
        await queryRunner.query(`ALTER TABLE \`fund_company_branches\` DROP FOREIGN KEY \`FK_359f33d325733255f26de719255\``);
        await queryRunner.query(`ALTER TABLE \`offers_lapor_sectors\` DROP FOREIGN KEY \`FK_5327fdc70b68bd4cf3bdd9e0014\``);
        await queryRunner.query(`ALTER TABLE \`offers_lapor_sectors\` DROP FOREIGN KEY \`FK_312d729856ff0972d3734f5da24\``);
        await queryRunner.query(`DROP INDEX \`IDX_554f4ad180601c22094fb2ff08\` ON \`collection_commission\``);
        await queryRunner.query(`DROP INDEX \`IDX_cff1a40d1ede76d09a950f7029\` ON \`collection_commission\``);
        await queryRunner.query(`DROP TABLE \`collection_commission\``);
        await queryRunner.query(`DROP INDEX \`IDX_b9a54d3ce9ed52bb803b481671\` ON \`agency_brands\``);
        await queryRunner.query(`DROP INDEX \`IDX_f16baced67c2f0c11dcc293891\` ON \`agency_brands\``);
        await queryRunner.query(`DROP TABLE \`agency_brands\``);
        await queryRunner.query(`DROP INDEX \`IDX_4bf592d2a8555fd51bbf371f62\` ON \`offers_agency\``);
        await queryRunner.query(`DROP INDEX \`IDX_5eb924cae75ea3be0d290e26fe\` ON \`offers_agency\``);
        await queryRunner.query(`DROP TABLE \`offers_agency\``);
        await queryRunner.query(`DROP INDEX \`IDX_ceaecb178638ac0accbf6fa32f\` ON \`offers_models\``);
        await queryRunner.query(`DROP INDEX \`IDX_1c9c8066b09d53b4001170baf5\` ON \`offers_models\``);
        await queryRunner.query(`DROP TABLE \`offers_models\``);
        await queryRunner.query(`DROP INDEX \`IDX_b5c09d453b6b02a377efbf6ce9\` ON \`offers_brands\``);
        await queryRunner.query(`DROP INDEX \`IDX_1431d2e8a870dc5e820086062a\` ON \`offers_brands\``);
        await queryRunner.query(`DROP TABLE \`offers_brands\``);
        await queryRunner.query(`DROP INDEX \`IDX_a548289995720460c08fb1dad8\` ON \`car_colors\``);
        await queryRunner.query(`DROP INDEX \`IDX_10bd402333a904e3db3992b7b6\` ON \`car_colors\``);
        await queryRunner.query(`DROP TABLE \`car_colors\``);
        await queryRunner.query(`DROP INDEX \`IDX_50cd5e8bd7cc7ea941e95e8a06\` ON \`admin_agency_branches\``);
        await queryRunner.query(`DROP INDEX \`IDX_4b785b347b331e3bca2272124c\` ON \`admin_agency_branches\``);
        await queryRunner.query(`DROP TABLE \`admin_agency_branches\``);
        await queryRunner.query(`DROP INDEX \`IDX_9fa6cfacbc967a05625a2334df\` ON \`admin_fund_branches\``);
        await queryRunner.query(`DROP INDEX \`IDX_41e32e3de92e4c88a4a81f0a2a\` ON \`admin_fund_branches\``);
        await queryRunner.query(`DROP TABLE \`admin_fund_branches\``);
        await queryRunner.query(`DROP TABLE \`collectioncommission\``);
        await queryRunner.query(`DROP TABLE \`commissions\``);
        await queryRunner.query(`DROP TABLE \`uploaded_files\``);
        await queryRunner.query(`DROP TABLE \`sub_models\``);
        await queryRunner.query(`DROP INDEX \`IDX_de137d31b741a0a88d9312dd04\` ON \`models\``);
        await queryRunner.query(`DROP INDEX \`IDX_53930e477ef83ab0a59b817259\` ON \`models\``);
        await queryRunner.query(`DROP TABLE \`models\``);
        await queryRunner.query(`DROP INDEX \`IDX_ae5f33d7567de896500debc24a\` ON \`brands\``);
        await queryRunner.query(`DROP INDEX \`IDX_15c9cb95a4bbc80a75f1995ecf\` ON \`brands\``);
        await queryRunner.query(`DROP TABLE \`brands\``);
        await queryRunner.query(`DROP INDEX \`IDX_ac29004bf7878d2cf5a5e09d28\` ON \`agencies\``);
        await queryRunner.query(`DROP INDEX \`IDX_d25d2a0363d82243de8434a2e7\` ON \`agencies\``);
        await queryRunner.query(`DROP INDEX \`IDX_2f561aed06ef50b06074ad9cf1\` ON \`agencies\``);
        await queryRunner.query(`DROP INDEX \`IDX_1ea16c73ecef4bab2f61c31c88\` ON \`agencies\``);
        await queryRunner.query(`DROP TABLE \`agencies\``);
        await queryRunner.query(`DROP TABLE \`offers\``);
        await queryRunner.query(`DROP TABLE \`requests\``);
        await queryRunner.query(`DROP TABLE \`requests_histories\``);
        await queryRunner.query(`DROP TABLE \`clients\``);
        await queryRunner.query(`DROP TABLE \`clients_score\``);
        await queryRunner.query(`DROP TABLE \`cars\``);
        await queryRunner.query(`DROP TABLE \`car_prices\``);
        await queryRunner.query(`DROP INDEX \`IDX_add54b5a317371786a73b8b152\` ON \`colors\``);
        await queryRunner.query(`DROP INDEX \`IDX_87478b727542707afa08266675\` ON \`colors\``);
        await queryRunner.query(`DROP INDEX \`IDX_7ebd35675297312bde25510454\` ON \`colors\``);
        await queryRunner.query(`DROP TABLE \`colors\``);
        await queryRunner.query(`DROP TABLE \`attachments_requests\``);
        await queryRunner.query(`DROP INDEX \`IDX_051db7d37d478a69a7432df147\` ON \`admins\``);
        await queryRunner.query(`DROP TABLE \`admins\``);
        await queryRunner.query(`DROP TABLE \`roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_7a146d49148e41cc8624762f3a\` ON \`agency_branches\``);
        await queryRunner.query(`DROP TABLE \`agency_branches\``);
        await queryRunner.query(`DROP TABLE \`fund_company_branches\``);
        await queryRunner.query(`DROP INDEX \`IDX_355cee4941a3d461e95fea2d45\` ON \`cities\``);
        await queryRunner.query(`DROP INDEX \`IDX_6c289e215c7d8c4ea3f274c914\` ON \`cities\``);
        await queryRunner.query(`DROP TABLE \`cities\``);
        await queryRunner.query(`DROP TABLE \`offers_lapor_sectors\``);
        await queryRunner.query(`DROP TABLE \`labor_sector\``);
        await queryRunner.query(`DROP INDEX \`IDX_651af7cc2b895f24487860cb40\` ON \`fund_companies\``);
        await queryRunner.query(`DROP INDEX \`IDX_c039cf3191de417c2162b77e93\` ON \`fund_companies\``);
        await queryRunner.query(`DROP INDEX \`IDX_1ef2fbb72e6a60223bee929411\` ON \`fund_companies\``);
        await queryRunner.query(`DROP INDEX \`IDX_02e5661a03de3391f8ddffb5dd\` ON \`fund_companies\``);
        await queryRunner.query(`DROP TABLE \`fund_companies\``);
    }

}
